type Uf {
  codUf: Int
  sigla: String
}

type Query {
  ufs: [Uf]
  uf(codUf: Int): Uf
}

input FiltroInput {
  codUf: Int
  siglaUf: String
}

input UfInput {
  codUf: Int
  sigla: String
}

type Mutation {
  criarUf(sigla: String): Uf
  criarUfs(data: [UfInput]): [Uf]
  atualizarUf(codUf: Int!, novaSigla: String): Uf
  deletarUf(filtro: FiltroInput): Boolean
}
